#!/usr/bin/env python3
"""A long timeline rendered in groups.

Rendered as ONE Wan2GP job, a long timeline keeps every finished window in
system RAM (wgp.py's `frames_already_processed`) and never lets the VRAM
baseline reset, which is why a twenty-clip piece dies partway through. In
groups, each group is its own job and both of those start clean again.

Groups are not independent takes, and that is the part worth testing: every
group after the first has to continue from the last `overlap` frames of the
one before it and run on the SAME seed, or the piece drifts at each boundary.
The carried frames get regenerated by the new group, so they must be trimmed
off its front at the join rather than appearing twice.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.join(HERE, "plugin.py")

fails = []


def check(label, ok, detail=""):
    print(("  OK   " if ok else "  FAIL ") + label + ("" if ok else "  -- " + detail))
    if not ok:
        fails.append(label)


src = open(PLUGIN, encoding="utf-8").read()


# --- the split itself ------------------------------------------------------
class Rig:
    pass


m = re.search(r"\n    def _group_plan\(self.*?(?=\n    def )", src, re.S)
assert m, "_group_plan not found"
body = "\n".join(l[4:] if l.startswith("    ") else l for l in m.group(0).split("\n"))
ns = {}
exec(compile("class _A:\n" + "\n".join("    " + l for l in body.split("\n")), "<x>", "exec"), ns)
Rig._group_plan = ns["_A"]._group_plan
r = Rig()

print("splitting the windows:")
wins = [243] * 20
g = r._group_plan(wins, 4)
check("20 windows in fours make 5 groups", len(g) == 5, str(len(g)))
check("every window lands in exactly one group",
      sum(len(x["windows"]) for x in g) == 20)
check("no window is lost or duplicated",
      [n for x in g for n in x["windows"]] == wins)
check("each group knows where it starts on the timeline",
      [x["start"] for x in g] == [0, 972, 1944, 2916, 3888],
      str([x["start"] for x in g]))
check("the starts line up with the frames before them",
      all(x["start"] == sum(wins[: i * 4]) for i, x in enumerate(g)))

g = r._group_plan([243] * 7, 3)
check("a remainder makes a shorter last group",
      [len(x["windows"]) for x in g] == [3, 3, 1], str([len(x["windows"]) for x in g]))
g = r._group_plan([243] * 3, 10)
check("a group bigger than the timeline is one group", len(g) == 1)
g = r._group_plan([243] * 3, 0)
check("a group size of zero does not divide by zero", len(g) == 3)

# --- what the render loop promises ----------------------------------------
print("\nwhat each group is sent:")
loop = re.search(r"\n    def _run_groups\(self.*?(?=\n    def )", src, re.S)
check("the group render loop exists", bool(loop))
loop = loop.group(0) if loop else ""

check("every group runs on the same seed",
      'st["seed"] = seed' in loop and "seed = int(base.get" in loop,
      "a per-job random seed would drift the look at every boundary")
check("a random seed is resolved ONCE, not per group",
      "seed was random; fixed at" in loop)
check("a later group continues from the previous group's tail",
      '_source_tail(prev_out, ovl, fps)' in loop)
check("and declares the continuation to Wan2GP",
      '"V" not in ipt' in loop and 'image_prompt_type' in loop,
      "without V in image_prompt_type the source video is ignored")
check("the carried frames are trimmed off the front at the join",
      "head_trim = carry" in loop and "trim_start_frames" in loop,
      "otherwise the overlap appears twice in the finished video")
check("a continued group is overlap frames LONGER than its share of the timeline",
      'st["video_length"] = int(grp["frames"]) + carry' in loop,
      "the group regenerates the carried frames, so without this it lands short")
check("and its slice of the song starts that much earlier",
      'audio_at = (grp["start"] - carry) / fps' in loop
      and 'audio_len = (grp["frames"] + carry) / fps' in loop,
      "otherwise the song drifts by one overlap at every group boundary")
check("the first group carries nothing, so neither applies to it",
      'carry = int(ovl) if prev_out else 0' in loop)
check("the first group carries nothing", "if prev_out:" in loop)
check("each group gets its own slice of the song",
      "_audio_slice(" in loop,
      "a job always starts its audio at 0:00, so the lip sync would reset")
check("each group gets its own prompt blocks",
      "blocks[w_at:w_at + n_win]" in loop)

# The bug Dave spotted before it shipped: a group is a separate job, so
# anything counted "ahead of the reference sheets" has to be counted for THAT
# group. numbering_offset covers the start image, the end image and injected
# frames; a middle group has neither start nor end, so keeping the whole
# timeline's offset would shift every picture number in its prompt.
check("each group is assembled from the PLAN, not from the finished prompt",
      "plan0 = dict(data.get" in loop and "_assemble_settings(pg)" in loop,
      "slicing an already-renumbered prompt keeps the wrong shift")
check("the start image goes only to the first group",
      'if not first_group and media_g.pop("image_start", None)' in loop)
check("the end image goes only to the last group",
      'if not last_group and media_g.pop("image_end", None)' in loop)
check("and the picture-number shift drops with them",
      "offset_g -= 1" in loop and 'pg["numbering_offset"] = max(0, offset_g)' in loop,
      "a group without the start image needs a smaller shift, or its prompt "
      "points at the wrong reference sheets")
check("the first group keeps exactly the offset a single job would use",
      "base_offset = plan0.get" in loop,
      "group 1 must render identically to an ungrouped run")
check("and the run says when a group's numbering differs",
      "picture numbers shifted by" in loop)

# "1 of 20 ... 22": the window number Wan2GP reports is within the group.
check("the window number is clamped to the group it came from",
      "min(int(js.get(\"window\") or 0), n_win - 1)" in loop,
      "window 4 of group 5 was being announced as window 22 of 20")
check("and progress names the group and the window in it",
      "Group %d of %d" in loop and "window %d of %d" in loop)
# The bug that reached a real run: the group split used the DEFAULT window
# plan (22 windows) while the prompt carried /duration tags, which put the
# render on the SCHEDULER (20 windows). The counts stopped matching, and the
# old fallback handed every group the whole prompt -- so all six groups each
# rendered the entire 20-window piece.
check("a mismatch REFUSES to group instead of falling back",
      "groups REFUSED" in loop and "Cannot render in groups" in loop,
      "handing every group the whole prompt renders the piece once per group")
check("the split follows the scheduler when the prompt carries duration tags",
      "plan_duration_frames(int(target), win, ovl, self._grid)[1]" in src,
      "the default plan gives a different window count, and then nothing lines up")
check("and the default plan only when it does not",
      "_real_plan_windows(int(target), win, ovl, self._grid)" in src)
check("hand-set windows still win over both", "if hand:" in src)
check("each group's produced length is checked against its slice",
      "LENGTH WARNING" in loop and "want_frames" in loop,
      "a group coming back the wrong length would only show as drift in the "
      "finished video")
check("the model is KEPT LOADED between groups by default",
      'release_between_groups", False)' in loop,
      "releasing between groups forces a full reload and does not free the "
      "video frames -- those go when the group's job returns")
check("but it can be turned on for a creeping VRAM baseline",
      "release_between and gi < n_groups - 1" in loop)
check("and the run says which it did", "keeping the model loaded" in loop)
check("the groups are joined at the end", "_join_videos(" in loop)
check("nothing is joined until every group is finished",
      loop.index("_join_videos(") > loop.rindex("submit(st)"),
      "joining inside the loop would put the whole video back in one process")
check("the model is let go at the END, once every group is rendered",
      "_release_model()\n\n        if len(parts)" in loop,
      "the work is finished by then, so there is nothing to reload for")
check("the join is a stream copy off disk, not a re-encode",
      '"-c", "copy"' in src,
      "decoding every group to re-encode would hold frames in memory again")
check("a failed join still hands back the group files",
      "could not be joined" in loop,
      "losing finished renders to a join error would be the worst outcome")
check("a cancelled group stops the run", 'frame("cancelled"' in loop)

# --- the drift that shows up as "it keeps getting brighter" ----------------
# Every window is generated from the encoded frames of the one before it, so a
# bias in that round trip is inherited and re-applied twenty times over. The
# measurement is unconditional: it turns a complaint about the finished video
# into a number, and rules the cause in or out.
print("\nlook drift across the joins:")
check("the look of the opening is measured once, off the first group",
      "look_ref = self._luma_stats(prev_out" in loop and "look_ref is None" in loop)
check("and every join is measured against it",
      "look drift at join" in loop,
      "without a number in the log, brightness drift is guesswork")
check("the drift is reported whether or not it is corrected",
      "if hold_look:" in loop and "else:" in loop)
check("correcting it is opt-in", 'hold_look_between_groups", False)' in loop,
      "a correction applied without asking would change every existing project")
check("the correction only touches the carried frames",
      'st["video_source"] = tail' in loop,
      "grading a finished group would re-encode the whole video")

hold = re.search(r"\n    def _hold_look\(self.*?(?=\n    def )", src, re.S)
hold = hold.group(0) if hold else ""
check("the correction exists", bool(hold))
check("it is capped per join", "cap=0.02" in hold and "max(-cap, min(cap" in hold,
      "a full correction at one boundary snaps the picture, which reads worse "
      "than the drift it fixes")
check("a drift too small to see is left alone", "abs(drift) < 0.004" in hold)
check("the corrected frames are still written losslessly", '"-crf", "0"' in hold)
check("a failure there carries the frames through untouched",
      "carrying the frames as they are" in hold and "return tail_path, drift" in hold)

luma = re.search(r"\n    def _luma_stats\(self.*?(?=\n    def )", src, re.S)
luma = luma.group(0) if luma else ""
check("brightness is measured with ffmpeg, not guessed",
      "signalstats" in luma and "YAVG" in luma)
check("and a clip it cannot measure returns nothing rather than zero",
      "if not vals:" in luma and "return None" in luma,
      "a zero reference would read as 100% drift and trigger a full correction")

# --- the release itself ----------------------------------------------------
print("\nreleasing the model:")
rel = re.search(r"\n    def _release_model\(self.*?(?=\n    def )", src, re.S)
rel = rel.group(0) if rel else ""
check("it calls Wan2GP's own release_model", 'getattr(wgp, "release_model"' in rel)

tail = re.search(r"\n    def _source_tail\(self.*?(?=\n    def )", src, re.S)
tail = tail.group(0) if tail else ""
check("the carried frames are written losslessly",
      '"-crf", "0"' in tail,
      "these frames decide the look of everything generated from them")
check("and survives a build that does not have it", "no release_model()" in rel)
check("a failure there does not stop the render", "continuing" in rel)

# --- the dispatch ----------------------------------------------------------
print("\nwhen groups are used:")
check("groups are off unless asked for", 'group_windows > 0' in src)
check("a timeline that fits in one group renders as before",
      "fits in one group of" in src)
check("a bridge pass never goes through groups", "not bridge_frames" in src)

print()
if fails:
    print("%d GROUP CHECK(S) FAILED" % len(fails))
    sys.exit(1)
print("ALL GROUP CHECKS PASSED")
