/**
 * Hover help, in one place.
 *
 * Every labelled control in the settings panes goes through `Row`, which looks
 * its label up here and hangs the text off the row as a tooltip. That way a
 * control gets help by being labelled, instead of by someone remembering to
 * add a `title` at each of a hundred call sites — which is how half of them
 * ended up with none.
 *
 * Keys are matched case-insensitively against the row's label, with
 * whitespace collapsed. Write plainly: these are read by someone who has just
 * opened the plugin for the first time.
 */

const HELP: Record<string, string> = {
  // ---- saved reference mods ----
  "strength": "How strongly this saved reference mod is applied. 1.00 is the strength it was saved at; above that exaggerates it, below eases it off.",
  "overall strength": "One multiplier over every mod's own strength, for easing the whole set back without touching each slider.",
  "add a mod": "Each mod you pick is added below the last. The order in the list is the order they are applied in.",
  // ---- model / generation ----
  "model": "Which MiniMax H3 checkpoint generates the video. Hybrid models accept both reference images and a soundtrack.",
  "checkpoint": "The exact model file Wan2GP loads. Finetunes you have built appear here alongside the stock models.",
  "pipeline": "FL2VA follows a start and end image. Ref2VA follows reference images. Hybrid does both.",
  "size": "Full is the 33B model, Pruned the smaller 20B. Pruned is faster and lighter on VRAM; Full holds detail better.",
  "resolution": "Output size. Larger costs time and VRAM on every window, so test at a smaller size first.",
  "resolution group": "Narrows the resolution list to one aspect ratio.",
  "number of inference steps": "Denoising steps per window. More is slower with diminishing returns; PDD checkpoints are trained for 8.",
  "guidance phases": "Denoising can run in more than one guidance phase. Each phase can carry its own LoRA strength.",
  "guidance scale": "How hard the model is pushed towards the prompt. Too high looks scorched and over-contrasted.",
  "flow shift": "Shifts the noise schedule. Higher favours large motion, lower favours fine detail.",
  "sample solver": "The sampler. Euler is the safe default and the only one some H3 checkpoints accept.",
  "seed": "Same seed with the same settings reproduces the same video. -1 picks a new one each time.",
  "videos per prompt": "Generate this many takes from the same settings, each with its own seed.",

  // ---- timeline / windows ----
  "fps": "Frames per second of the finished video. H3 is trained at 24; changing it changes how frame counts map to seconds.",
  "duration (s)": "How long the finished video is. This is what comes out — set it to your soundtrack's length to cover it.",
  "window": "Frames generated in one pass, about 15 seconds at 24fps. The timeline is covered by as many passes as it takes.",
  "overlap": "Frames re-generated at each join so the seam matches. More costs time; too little shows a visible cut.",
  "sliding window size": "Frames generated in one pass. Larger windows hold continuity better but need more VRAM.",
  "sliding window overlap": "Frames shared between one window and the next, to keep the join invisible.",
  "hard-cuts": "Window numbers that start a new shot instead of continuing the last one. Separate with spaces.",

  // ---- references / injection ----
  "reference images": "Sheets that keep a character, outfit or place consistent. Refer to them by number in a prompt.",
  "reference sheet size": "How large the sheets are rendered into the conditioning. Raise it when a reference is not asserting itself.",
  "control / inject": "How the control video and injected frames are handed to the model.",
  "denoising strength": "How far the result may drift from the control video. At 1.0 with Whole Frame the control video is skipped entirely.",
  "masking strength": "How closely the area outside the mask stays with the control video.",

  // ---- audio ----
  "audio source": "Where the soundtrack comes from: a file you supply, the control video's own audio, or generated by the model.",
  "no music": "When the model is generating the audio, ask it not to write music.",
  "no speech": "When the model is generating the audio, ask it not to produce voices.",
  "no ambience": "When the model is generating the audio, ask it not to add room tone or background.",
  "no effects": "When the model is generating the audio, ask it not to add sound effects.",

  // ---- sound design ----
  "sound design": "Runs MMAudio over a finished video to add effects. Works on any video, not only this project.",
  "separate sfx track": "Write the effects as their own audio file as well, so you can mix them in a DAW.",

  // ---- output ----
  "project name": "Used for the saved project and the output file names.",
  "save folder": "Where Save project writes its zip. Autosave does not use this.",
};

function norm(label: string): string {
  return String(label || "").toLowerCase().replace(/\s+/g, " ").trim().replace(/[:：]$/, "");
}

/** Hover text for a labelled control, or undefined when there is none. */
export function helpFor(label: string): string | undefined {
  const key = norm(label);
  if (!key) return undefined;
  if (HELP[key]) return HELP[key];
  // Tolerate a label that carries a unit or a qualifier, e.g. "Overlap (frames)".
  const bare = key.replace(/\s*\([^)]*\)\s*$/, "").trim();
  return HELP[bare];
}

export default HELP;
